### ISSUE TITLE
If you're varying IC in this script, why are you also varying g_Leak?

### ISSUE THREAD

**Issue by sg-s** [btromm/neuralcorr-thesis#5]
https://github.com/btromm/neuralcorr-thesis/blob/514bd3a150e9060c8ae3275108ee2a83b1753235/variation/variation_ic.m#L13

**Comment by sg-s** [comment]
also look at linspace()

**Comment by btromm** [comment]
Replaced either of these in favor of randomizing b/w a set interval

**Comment by btromm** [comment]
(Also eliminated varying g_Leak, that was an artifact)
