### ISSUE TITLE
construct the model only once

### ISSUE THREAD

**Issue by sg-s** [btromm/neuralcorr-thesis#6]
https://github.com/btromm/neuralcorr-thesis/blob/514bd3a150e9060c8ae3275108ee2a83b1753235/variation/variation_ic.m#L22

**Comment by btromm** [comment]
Don't I need to measure Ca_target for all values of leak?

**Comment by sg-s** [comment]
No -- the g_Leak is your perturbation. Your "reference model" is one particular model, with one particular g_Leak. So the parameters of your regulation (Ca_target, tau_ms) are the same for all conditions.

**Comment by sg-s** [comment]
No -- the g_Leak is your perturbation. Your "reference model" is one particular model, with one particular g_Leak. So the parameters of your regulation (Ca_target, tau_ms) are the same for all conditions.
